/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "D0.h"
#include "D0_aliases.h"
#include "D1.h"
#include "D1_aliases.h"
#include "D2.h"
#include "D2_aliases.h"
#include "D3.h"
#include "D3_aliases.h"
#include "D4.h"
#include "D4_aliases.h"
#include "D5.h"
#include "D5_aliases.h"
#include "D6.h"
#include "D6_aliases.h"
#include "D7.h"
#include "D7_aliases.h"
#include "CK.h"
#include "CK_aliases.h"
#include "OE.h"
#include "OE_aliases.h"
#include "Q0.h"
#include "Q0_aliases.h"
#include "Q1.h"
#include "Q1_aliases.h"
#include "Q2.h"
#include "Q2_aliases.h"
#include "Q3.h"
#include "Q3_aliases.h"
#include "Q4.h"
#include "Q4_aliases.h"
#include "Q5.h"
#include "Q5_aliases.h"
#include "Q6.h"
#include "Q6_aliases.h"
#include "Q7.h"
#include "Q7_aliases.h"
#include "LED_OK.h"
#include "LED_OK_aliases.h"
#include "LED_FAIL.h"
#include "LED_FAIL_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

